### ISSUE TITLE
Cosmos example subgraphs: Update graph-ts dependency version from 0.27.0 to 0.29.0 in package.json

### ISSUE THREAD

**Issue by milos1991** [graphprotocol/example-subgraphs#4]
This is more of an improvement than an issue - when i was following [EventHandler](https://github.com/graphprotocol/example-subgraphs/tree/main/cosmos/osmosis-token-swaps) example on Cosmos network, I've installed the `graph-ts` version `0.27.0` (as in the example) and then I tried to get transaction information from `EventData` object, however this was added in `0.29.0`.

Maybe it would be good to update this version in examples, even though transaction data is not extracted from `EventData` in the EventHandler example - this could be helpful in order to prevent questions like "where is the transaction related information from EventData object?".

**Comment by azf20** [comment]
Thanks! These examples have been migrated to the [Graph Tooling repository](https://github.com/graphprotocol/graph-tooling)
